<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf85c5c2aa3c4099860da9ffd7d0c216b
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Cocur\\Slugify\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Cocur\\Slugify\\' => 
        array (
            0 => __DIR__ . '/..' . '/cocur/slugify/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf85c5c2aa3c4099860da9ffd7d0c216b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf85c5c2aa3c4099860da9ffd7d0c216b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf85c5c2aa3c4099860da9ffd7d0c216b::$classMap;

        }, null, ClassLoader::class);
    }
}
