<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitf85c5c2aa3c4099860da9ffd7d0c216b
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitf85c5c2aa3c4099860da9ffd7d0c216b', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitf85c5c2aa3c4099860da9ffd7d0c216b', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitf85c5c2aa3c4099860da9ffd7d0c216b::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
