<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit022b479b3aa02f728f79468e96abd4a1
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'League\\CommonMark\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'League\\CommonMark\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/commonmark/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit022b479b3aa02f728f79468e96abd4a1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit022b479b3aa02f728f79468e96abd4a1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit022b479b3aa02f728f79468e96abd4a1::$classMap;

        }, null, ClassLoader::class);
    }
}
